export {BaseDocumentMerger} from './BaseDocumentMerger'
export {BaseDocumentSerializer} from './BaseDocumentSerializer'
export {BaseDocumentDeserializer} from './BaseDocumentDeserializer'
export {defaultStopTypes, customSerializers} from './BaseSerializationConfig'
export {Dummy} from './Dummy'
